stages:
 - test

cache:
  paths:
  - .cache/

variables:
  GIT_DEPTH: "3"

.test-template: &test
  stage: test
  before_script:
    - apt-get -q update
    - env DEBIAN_FRONTEND=noninteractive apt-get -q -y -o dir::cache::archives=".cache" build-dep .
    - time t/bin/build-test-packages-if-needed .cache
  script:
    - time t/bin/runtests

unstable:
  <<: *test
  image: debian:unstable

testing:
  <<: *test
  image: debian:testing

stable-bpo:
  <<: *test
  image: debian:stable-backports
